### ISSUE TITLE
Multiline Strings Aren't Parsed Accurately

### ISSUE THREAD

**Issue by Nolij** [Nolij/ZSON#2]
https://github.com/Nolij/ZSON/blob/master/src/test/java/ZsonTest.java#L123-L124

Assigned to @rhysdh540 (GitHub doesn't allow assigning to non-contributors apparently?)

**Comment by rhysdh540** [comment]
"non-contributor" 💀

**Comment by rhysdh540** [comment]
I believe that not excluding indents is a part of the JSON5 spec. So, the test is wrong and not the parser.
